name: Reusable Build and Test


on:
  workflow_call:
    inputs:
      test_linux:
        type: boolean
        default: true
        description: "Run Linux Build and Test"
      test_windows:
        type: boolean
        default: true
        description: "Run Windows Build and Test" 
      test_macintosh:
        type: boolean
        default: true
        description: "Run Mac OS Build" 
      upload_artifacts:
        type: boolean
        default: true
        description: "Upload Artifacts"
      version:
        required: false
        type: string

jobs:
  build_and_test_linux:
    if: ${{ inputs.test_linux }}
    name: "Build and test on Linux 👍"
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
    runs-on: [self-hosted, "${{ matrix.arch == 'x86_64' && 'X64' || 'ARM64' }}"]
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Memgraph Container Without SSL
        run: |
          docker network create pymgclient-network || echo "Network already exists"
          docker run -d --rm --name memgraph --network pymgclient-network memgraph/memgraph:latest \
            --telemetry-enabled=false

      - name: Run Memgraph Container With SSL
        run: |
          docker run -d --rm --name memgraph-ssl --network pymgclient-network memgraph/memgraph:latest \
            --telemetry-enabled=false \
            --bolt-cert-file=/etc/memgraph/ssl/cert.pem \
            --bolt-key-file=/etc/memgraph/ssl/key.pem

      - name: Build Docker Image
        run: |
          docker buildx build \
            --platform linux/${{ matrix.arch }} \
            -t pymgclient-builder:latest \
            --build-arg PYTHON_VERSIONS="3.10,3.11,3.12,3.13,3.14" \
            -f tools/Dockerfile.manylinux \
            --load .

      - name: Launch Docker Container
        run: |
          if [[ "${{ inputs.version }}" != "" ]]; then
            echo "Building version ${{ inputs.version }}"
            docker run -d --rm -e PYMGCLIENT_OVERRIDE_VERSION=${{ inputs.version }} --name testcontainer --network pymgclient-network pymgclient-builder:latest    
          else
            docker run -d --rm --name testcontainer --network pymgclient-network pymgclient-builder:latest   
          fi

      - name: Build Python Wheels
        run: |
          PYTHON_VERSIONS=("3.10" "3.11" "3.12" "3.13" "3.14")
          for python_version in "${PYTHON_VERSIONS[@]}"; do
            build_cmd="./tools/build-wheel-manylinux.sh --python-version $python_version --static-ssl --run-auditwheel"
            docker exec -i testcontainer \
              bash -c "cd /home/memgraph/pymgclient && $build_cmd"
          done

          # list the wheels
          docker exec -i testcontainer \
            bash -c "ls -la /home/memgraph/pymgclient/dist"

      - name: Install pymgclient and run tests
        run: |
          PYTHON_VERSIONS=("3.10" "3.11" "3.12" "3.13" "3.14")
          for python_version in "${PYTHON_VERSIONS[@]}"; do
            echo "Testing Python version $python_version"
            short_python_version=$(echo $python_version | sed 's/\.//g')
            docker exec -i testcontainer \
              bash -c "python$python_version -m pip install \$(ls /home/memgraph/pymgclient/dist/pymgclient*cp${short_python_version}*.whl) --break-system-packages"
            docker exec -i testcontainer \
              bash -c "python$python_version -c 'import mgclient'"
            docker exec -i testcontainer \
              bash -c "export MEMGRAPH_HOST=memgraph && cd /home/memgraph/pymgclient && python$python_version -m pytest -v"
            docker exec -i testcontainer \
              bash -c "export MEMGRAPH_STARTED_WITH_SSL=true && export MEMGRAPH_HOST=memgraph-ssl && cd /home/memgraph/pymgclient && python$python_version -m pytest -v"
          done

      - name: Build docs
        run: |
          docker exec -i testcontainer \
            bash -c "cd /home/memgraph/pymgclient/docs && make html"

      - name: Copy Packages
        run: |
          docker cp testcontainer:/home/memgraph/pymgclient/dist .

      - name: Save Packages
        if: ${{ inputs.upload_artifacts }}
        uses: actions/upload-artifact@v4
        with:
          name: pymgclient-linux-${{ matrix.arch }}
          path: dist/*

      - name: Cleanup
        if: always()
        run: |
          docker stop testcontainer || echo "Container does not exist"
          docker wait testcontainer || echo "Container does not exist"
          docker stop memgraph || echo "Memgraph container does not exist"
          docker wait memgraph || echo "Memgraph container does not exist"
          docker stop memgraph-ssl || echo "Memgraph container with SSL does not exist"
          docker wait memgraph-ssl || echo "Memgraph container with SSL does not exist"
          docker rmi pymgclient-builder:latest || echo "Image does not exist"
          docker network rm pymgclient-network || echo "Network does not exist"

          
  build_and_test_windows:
    if: ${{ inputs.test_windows }}
    name: Build and Test on Windows
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-2025]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set override version if provided
        if: ${{ inputs.version != '' }}
        shell: bash
        run: |
          echo "Building version ${{ inputs.version }}"
          echo "PYMGCLIENT_OVERRIDE_VERSION=${{ inputs.version }}" >> $GITHUB_ENV

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >
            git
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make
            mingw-w64-x86_64-openssl
      
      - name: Add MSYS2 mingw64/bin to PATH
        shell: msys2 {0}
        run: |
          echo "/mingw64/bin" >> $GITHUB_PATH
          
              
      - name: Set up Windows Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Add Windows Python to PATH
        shell: msys2 {0}
        run: |
          echo "$pythonLocation" >> $GITHUB_PATH
        env:
          pythonLocation: ${{ env.pythonLocation }}
      

      - name: Install Python build tools
        shell: msys2 {0}
        run: |
          export PATH="$(cygpath -u "$pythonLocation"):$PATH"
          python -m pip install --upgrade pip setuptools wheel pyopenssl pytest tzdata build
        env:
          pythonLocation: ${{ env.pythonLocation }}
          
      - name: Build pymgclient Wheel
        shell: msys2 {0}
        run: |
          export PATH="$(cygpath -u "$pythonLocation"):$PATH"
          python -m build
        env:
          pythonLocation: ${{ env.pythonLocation }}

      - name: Install built wheel
        shell: msys2 {0}
        run: |
          export PATH="$(cygpath -u "$pythonLocation"):$PATH"
          python -m pip install dist/*.whl
        env:
          pythonLocation: ${{ env.pythonLocation }}

      - name: Setup WSL Ubuntu
        uses: Vampire/setup-wsl@v5
        with:
          distribution: Ubuntu-24.04

      - name: Set Memgraph Version
        shell: bash -l {0}
        run: |
          mgversion=$(./tools/get_memgraph_version.sh)
          echo "MGVERSION=$mgversion" >> $GITHUB_ENV

      - name: Install and Run Memgraph in WSL
        shell: wsl-bash {0}
        run: |
          mkdir -p $HOME/memgraph/data
          sudo apt update
          sudo apt install -y curl
          curl -L https://download.memgraph.com/memgraph/v${{ env.MGVERSION }}/ubuntu-24.04/memgraph_${{ env.MGVERSION }}-1_amd64.deb -o memgraph.deb
          sudo mkdir -p /etc/systemd/system && sudo ln -s /dev/null /etc/systemd/system/memgraph.service # Prevents Memgraph from starting.
          sudo apt install -y ./memgraph.deb
          openssl req -x509 -newkey rsa:4096 -days 3650 -nodes -keyout key.pem -out cert.pem -subj "/C=GB/ST=London/L=London/O=Testing Corp./CN=PymgclientTest"
          nohup /usr/lib/memgraph/memgraph --bolt-port 7687 --bolt-cert-file="cert.pem" --bolt-key-file="key.pem" --data-directory="~/memgraph/data" --storage-properties-on-edges=true --storage-snapshot-interval-sec=0 --storage-wal-enabled=false --storage-snapshot-on-exit=false --telemetry-enabled=false --log-file='' &
      
          # sleep here instead of using script because it just doesn't work in Windows
          sleep 3
          # sed $'s/\r$//' ./tools/wait_for_memgraph.sh > ./tools/wait_for_memgraph.unix.sh
          # bash ./tools/wait_for_memgraph.unix.sh localhost
      

      - name: Run Tests
        shell: msys2 {0}
        run: |
          export PATH="$(cygpath -u "$pythonLocation"):/mingw64/bin:$PATH"
          echo $PATH
          python -m pytest -v 

        env:
          pythonLocation: ${{ env.pythonLocation }}
          MEMGRAPH_HOST: localhost
          MEMGRAPH_STARTED_WITH_SSL:
      

      - name: Upload Wheel Artifact
        if: ${{ inputs.upload_artifacts && matrix.os == 'windows-2025' }}
        uses: actions/upload-artifact@v4
        with:
          name: pymgclient-win-${{ matrix.python-version }}
          path: dist/


  # NOTE: Cannot run tests on Mac OS runners because:
  # - GitHub hosted runners don't have docker
  # - self-hosted runner unable to log in to docker due to requiring a password to unlock the keychain
  # Also - github hosted macos runners after macos-13 are all arm64
  build_macos:
    if: ${{ inputs.test_macintosh }}
    name: Build and test on MacOS
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-14, macos-15]
        python_version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Set override version if provided
        if: ${{ inputs.version != '' }}
        run: |
          echo "Building version ${{ inputs.version }}"
          echo "PYMGCLIENT_OVERRIDE_VERSION=${{ inputs.version }}" >> $GITHUB_ENV

      - name: Install python and OpenSSL
        run: |
          brew install python@${{ matrix.python_version }} openssl@1.1
          brew link --force --overwrite openssl@1.1
          openssl version -a

      - name: Manage OpenSSL 3 on ARM machines
        if: ${{ contains(matrix.platform, 'ARM64') }}
        run: |
          brew install openssl@3
          brew link --force --overwrite openssl@3
          openssl version -a

      - name: Make used python version default
        run: |
          brew unlink python@3 && brew link --force python@${{ matrix.python_version }}
          python${{ matrix.python_version }} --version

      - name: Create Virtual Env
        run: |
          python${{ matrix.python_version }} -m venv env

      - name: Install pytest and pyopenssl
        run: |
          export PIP_BREAK_SYSTEM_PACKAGES=1
          source env/bin/activate
          python${{ matrix.python_version }} -m pip install pyopenssl pytest setuptools build

      - name: Build pymgclient
        run: |
          source env/bin/activate
          python${{ matrix.python_version }} -m build

      - name: Install pymgclient
        run: |
          export PIP_BREAK_SYSTEM_PACKAGES=1
          source env/bin/activate
          python${{ matrix.python_version }} -m pip install dist/*.whl

      - name: Import mgclient to validate installation
        run: |
          source env/bin/activate
          python${{ matrix.python_version }} -c "import mgclient"

      - name: Save wheel package
        if: ${{ inputs.upload_artifacts }}
        uses: actions/upload-artifact@v4
        with:
          name: pymgclient-${{ matrix.platform[0] || matrix.platform }}-${{ matrix.python_version }}
          path: dist/*.whl

